### ISSUE TITLE
Forwarding Props done right?

### ISSUE THREAD

**Issue by kay-is** [robinpowered/glamorous-native#53]
- `glamorous-native` version: 1.1.0
- `react-native` version: 0.44.2
- `react` version: 16.0.0-alpha.6

Relevant code:

```javascript
MyButton.js:

import React from "react";
import Button from "react-native-button";
import glamorous from "glamorous-native";

const baseStyle = {
  width: 270,
  paddingVertical: 10
};

const primaryStyle = {
  color: "#ffffff",
  backgroundColor: "#111111"
};

const secondaryStyle = {
  color: "#111111",
  borderColor: "#111111",
  borderWidth: 1
};

export default glamorous(Button)(
  baseStyle,
  props => (props.type === "primary" ? primaryStyle : secondaryStyle)
);

SomeFile.js:

import MyButton from "./MyButton";
...
return <MyButton onPress={...} marginBottom={10}>Lets Go</MyButton>
```

What you did:

I used `react-native-button` because it can be styled with CSS and then tried to style it with the help of `glamorous-native`

What happened:

The `marginBottom` prop I used when creating an instance wasn't used, but the `onPress` worked.

Problem description:

It seems that the components that are included in `glamorous-native` can be used like this:

    <Text color="red" margin={10}">Hello</Text>

But the custom ones, I created with the help of `glamorous-native` can't

Suggested solution:

No idea. Did I do something wrong at the definition? Is this generally not possible?

**Comment by ajwhite** [comment]
Hey @kay-is -- what you want to do here for the "props as styles" is add the following static property to your component:

```diff
-export default glamorous(Button)(
+const StyledButton = glamorous(Button)(
   baseStyles,
   props => (props.type === "primary" ? primaryStyle : secondaryStyle)
 )
+StyledButton.propsAreStyleOverrides = true
+export default StyledButton
```

That will let you do things like
```js
<StyledButton margin={10} />
```

**Comment by kay-is** [comment]
Thanks for the quick answer :)

But still the `onPress` works, but the `margin` doesn't :/

**Comment by ajwhite** [comment]
Would you be able to share your updated files, perhaps in a gist? Ideally the implementation file of the button, and the file integrating the button into a UI

**Comment by kay-is** [comment]
I just added your changes.

    import React from "react";
    import Button from "react-native-button";
    import glamorous from "glamorous-native";

    const baseStyle = {
      width: 270,
      paddingVertical: 10
    };

    const primaryStyle = {
      color: "#ffffff",
      backgroundColor: "#111111"
    };

    const secondaryStyle = {
      color: "#111111",
      borderColor: "#111111",
      borderWidth: 1
    };

    const StyledButton = glamorous(Button)(
      baseStyle,
      props => (props.type === "primary" ? primaryStyle : secondaryStyle)
    );

    StyledButton.propsAreStyleOverrides = true;

    export default StyledButton;

I used this button: https://github.com/ide/react-native-button/blob/master/Button.js

**Comment by ajwhite** [comment]
Thanks!

I tried to reproduce this with `react-native` components (`View`, `Text`, etc) and it works fine -- I'm wondering if `react-native-button`'s implementation is doing anything weird here. 

I think a helpful next step might be to set up a quick repo with this reproduced and I can run through and see what I can pick up

**Comment by kay-is** [comment]
Okay, made a repo here: https://github.com/kay-is/style-props-test

**Comment by ajwhite** [comment]
Ah! Thanks for putting that together, made digging into this much easier.

Since `react-native-button` is a higher order component, it goes undetected by the [style property detector `isStyleProp`](https://github.com/robinpowered/glamorous-native/blob/35ec3680021bc44d8b38d56785461ccdc871b15d/src/is-style-prop.js#L46-L56).

It essentially takes `Button` from `react-native-button` and checks to see if it exists in `viewStyleComponents` or `textStyleComponents` to determine which style PropTypes to examine.

For higher order components, there's a `glamorous` option you can pass called [`rootEl`](https://github.com/robinpowered/glamorous-native#rootel) -- this will allow you to specify what the lower order component is, in this case, I believe [the style becomes associated to a `Text` node](https://github.com/ide/react-native-button/blob/master/Button.js#L58).


## Your quick fix

Update to:
```js
const StyledButton = glamorous(Button, {rootEl: Text})(
```

https://github.com/kay-is/style-props-test/compare/master...ajwhite:fix

## Longer, more ideal fix

Patching this library to attempt to examine the component's `propTypes` to see if there's a `style` property type, and if so, attempt to examine its shape for more intelligent style-as-prop detection

**Comment by kay-is** [comment]
Nice, thanks.

I fiddled around with `forwardProps` and `rootEl` once, but I thought the right Component was `TouchableOpacity`, so it didn't work.
