### ISSUE TITLE
Safer prop forwarding

### ISSUE THREAD

**Issue by ajwhite** [robinpowered/glamorous-native#9]
Prop forwarding is currently using a naive approach of verifying the property is not a style prop name: [src/is-style-prop](https://github.com/robinpowered/glamorous-native/blob/master/src/is-style-prop.js)

It should verify the property is allowed by the component. A trivial solution here would be to check the type of component (eg, a `ListView`), and verify the property exists in the component's `propTypes`

**Comment by ssomnoremac** [comment]
I can look into this. I noticed that this isn't working though:

```
const BigText = glamorous.text({fontSize: 20})

<BigText color='blue' />
```

The fontSize is 20 but the color is not blue. I'll look into that as well.

**Comment by ajwhite** [comment]
That should be the same behavior as in `glamorous`, if @kentcdodds could confirm.

"properties as styles" is only supported when the [component class has `propsAreStyleOverrides = true`](https://github.com/robinpowered/glamorous-native/blob/bcce4428323bf420c18a02be3d9c43cf5991f967/src/index.js#L27) defined on it.

Your example would work with the following changes:

```diff
 const BigText = glamorous.text({fontSize: 20})
+BigText.propsAreStyleOverrides = true

 <BigText color='blue' >Hi</BigText>
```

**Comment by ajwhite** [comment]
The built-in components all have `propsAreStyleOverrides` enabled, which is why the following works

```jsx
<glamorous.Text color="blue">Blue text</glamorous.Text>
```

**Comment by ajwhite** [comment]
IMO `propsAreStyleOverrides` should be allowed as an option in `glamorous(Comp, opts)`

**Comment by kentcdodds** [comment]
Confirmed, this is by design :+1:

**Comment by kentcdodds** [comment]
Note: another way to accomplish what you're after would be:

```javascript
const BigText = glamorous.text({fontSize: 20})

<BigText css={{color: 'blue'}}>Hi</BigText>
```

**Comment by lewisl9029** [comment]
> Note: another way to accomplish what you're after would be:
> 
> ```js
> const BigText = glamorous.text({fontSize: 20})
> 
> <BigText css={{color: 'blue'}}>Hi</BigText>
> ```

I'm fairly new to react-native and glamorous-native, so this could be a dumb question, but I'm wondering if the above example (with the `css={{color: 'blue'}}` prop) has an equivalent in glamorous-native? If not, are there any plans to add the `css` prop to glamorous-native components? 

My current preference with glamorous on the web is to use the `css` prop over the component factories because it allows you to have styles immediately visible in-context inside your component tree.

Right now I'm using a custom shim over the glamorous-native factories to pick off the css prop and apply it as the args to each factory to maintain a consistent API:

```js
const create = React.createElement

const glamorousFactoryArgs = (css) => F.unnest(F.append(css, []))

const withCssProp = (glamorousFactory) => ({ css, ...props }) =>
  create(glamorousFactory(...glamorousFactoryArgs(css)), props)
```

But it'd be great if there was an officially supported way to accomplish the same thing.

I'm totally willing to take some time to look into this and make a PR if this is something desirable but not high enough priority for the primary maintainers to work on at the moment.

**Comment by ajwhite** [comment]
Hi @lewisl9029 -- React Native uses the `style` prop to pass styles to components. It's essentially equivalent to `css`, but it also accepts arrays.

Example:

```js
const BigText = glamorous.text({fontSize: 20})

<BigText style={{color: 'blue'}}>Hi</BigText>
```

**Comment by lewisl9029** [comment]
Ah that makes a ton of sense. For some reason I had the impression that you could only use `style` in React Native with the stylesheet references from the props of whatever gets returned by `StyleSheet.create()`. But if you could simply pass in plain style objects, that would be perfect.
